apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: laboratorio
type: Opaque
stringData:            # stringData aceita texto puro — o K8s converte pra base64
  DB_PASSWORD: "minha-senha-secreta"
  API_KEY: "abc123xyz"