apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: project
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
  POSTGRES_PASSWORD: "postgres"
