apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  namespace: laboratorio
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "infinity"]   # mantém o container vivo para inspecionarmos

      # Forma 1 — variáveis de ambiente vindas do ConfigMap
      envFrom:
        - configMapRef:
            name: app-config       # injeta TODAS as chaves como env vars
        - secretRef:
            name: app-secret       # variáveis sensíveis
  restartPolicy: Never